### ISSUE TITLE
TKReader using TKAReader1 as one of its members (specific to analyzer1)

### ISSUE THREAD

**Issue by yeskarthik** [vanlehn/seatr#10]
public class TKReader implements TKReaderI{

```
private boolean replace;
private TKAReader1[] tkaReader;
```

.....

Shouldn't it be generic and not be specific to analyzer 1? if it is then shouldn't it be called TKReader1

**Comment by dikshayp** [comment]
We cant keep it generic as it leads to mapping error. Intially i had kept it generic, hence the name TKReader. But now, since it is specific to a analyzer, we should rename it to TKReader1

**Comment by dikshayp** [comment]
Name changed. Pushed to branch cascade. Please Review.
